<script>
  import liff from "@line/liff";
  import { fade } from "svelte/transition";
  import Pic from "./component/Pic.svelte";
  import { myPic } from './stores.js';

  let isInClient = false;
  let liffInit = initLiff();

  async function initLiff() {
    await liff
      .init({
        liffId: "1654061887-ZoYpPWL2",
      })
      .then(() => {
        // start to use LIFF's api
        displayLiffData();
      })
      .catch((err) => {
        window.alert("請檢察網路連線問題");
	  });
	  
	  await liff
      .getProfile()
      .then((profile) => {
        name = profile.displayName;
        myPic.set(profile.pictureUrl);
      })
      .catch((err) => {
        console.log("error", err);
  });
  }
  //   onMount(initLiff());
  /**
   * Display data generated by invoking LIFF methods
   */
  function displayLiffData() {
    isInClient = liff.isInClient();
  }
</script>

<style>
</style>
{#await liffInit}
  <div />
{:then}
  {#if !isInClient}
    <h1>請移至line中開啟</h1>
  {:else}
    <div transition:fade>
      <Pic />
    </div>
  {/if}
{:catch error}
  <p>{error.message}</p>
{/await}
