<script>
  import liff from "@line/liff";
  import { onMount } from "svelte";

  let s = ''
  let picUrl = ''

  onMount(async () => {
    // 	let myLiffId = "1654061887-ZoYpPWL2";
    // const res =  await fetch(`https://www.google.com`)
    // s = res
    await liff
      .init({
        liffId: "1654061887-ZoYpPWL2",
      })
      .then(() => {
        // start to use LIFF's api
        displayLiffData();
        s = "YY";
      })
      .catch((err) => {
        window.alert("err:" + err);
      });

    await liff
      .getProfile()
      .then((profile) => {
		const name = profile.displayName;
		picUrl = profile.pictureUrl
      })
      .catch((err) => {
        console.log("error", err);
      });
  });

  /**
   * Initialize LIFF
   * @param {string} myLiffId The LIFF ID of the selected element
   */
  // function initializeLiff(myLiffId) {

  // }

  /**
   * Initialize the app by calling functions handling individual app components
   */
  /**
   * Display data generated by invoking LIFF methods
   */
  let isInClient = "123";
  function displayLiffData() {
    isInClient = liff.isInClient();
  }

  function shereMsg() {
    if (liff.isApiAvailable("shareTargetPicker")) {
      liff
        .shareTargetPicker([
          {
            type: "text",
            text: "Hello",
          },
        ])
        .then((isInClient = "success"))
        .catch(function (res) {
          isInClient = "err";
        });
    }
  }
</script>

<p>isInClient: {isInClient}</p>
<p>{picUrl}</p>
<button on:click={shereMsg}>shere</button>
