<script>
  import liff from "@line/liff";
  import { onMount } from "svelte";

  let s = "";
  let picUrl = "";
  let name = "";
  let text = "";

  onMount(async () => {
    // 	let myLiffId = "1654061887-ZoYpPWL2";
    // const res =  await fetch(`https://www.google.com`)
    // s = res
    await liff
      .init({
        liffId: "1654061887-ZoYpPWL2",
      })
      .then(() => {
        // start to use LIFF's api
        displayLiffData();
        s = "YY";
      })
      .catch((err) => {
        window.alert("err:" + err);
      });

    await liff
      .getProfile()
      .then((profile) => {
        name = profile.displayName;
        picUrl = profile.pictureUrl;
      })
      .catch((err) => {
        console.log("error", err);
      });
  });

  /**
   * Initialize LIFF
   * @param {string} myLiffId The LIFF ID of the selected element
   */
  // function initializeLiff(myLiffId) {

  // }

  /**
   * Initialize the app by calling functions handling individual app components
   */
  /**
   * Display data generated by invoking LIFF methods
   */
  let isInClient = "123";
  function displayLiffData() {
    isInClient = liff.isInClient();
  }

  function shareMsg() {
    if (liff.isApiAvailable("shareTargetPicker")) {
      liff
        .shareTargetPicker([
          {
            type: "flex",
            altText: "Hello",
            contents: {
              type: "bubble",
              body: {
                type: "box",
                layout: "vertical",
                contents: [
                  {
                    type: "image",
                    url: picUrl,
                    size: "full",
                    aspectMode: "cover",
                    aspectRatio: "1:1",
                    gravity: "center",
                  },
                  {
                    type: "image",
                    url:
                      "https://scdn.line-apps.com/n/channel_devcenter/img/flexsnapshot/clip/clip15.png",
                    position: "absolute",
                    aspectMode: "fit",
                    aspectRatio: "1:1",
                    offsetTop: "0px",
                    offsetBottom: "0px",
                    offsetStart: "0px",
                    offsetEnd: "0px",
                    size: "full",
                  },
                  {
                    type: "box",
                    layout: "horizontal",
                    contents: [
                      {
                        type: "box",
                        layout: "vertical",
                        contents: [
                          {
                            type: "box",
                            layout: "horizontal",
                            contents: [
                              {
                                type: "text",
                                text: name + ": " + text,
                                size: "xl",
                                color: "#ffffff",
                              },
                            ],
                          },
                          {
                            type: "box",
                            layout: "horizontal",
                            contents: [
                              {
                                type: "box",
                                layout: "baseline",
                                contents: [
                                  {
                                    type: "text",
                                    text: "¥62,000",
                                    color: "#ffffff",
                                    size: "md",
                                    flex: 0,
                                    align: "end",
                                  },
                                  {
                                    type: "text",
                                    text: "¥82,000",
                                    color: "#a9a9a9",
                                    decoration: "line-through",
                                    size: "sm",
                                    align: "end",
                                  },
                                ],
                                flex: 0,
                                spacing: "lg",
                              },
                            ],
                          },
                        ],
                        spacing: "xs",
                      },
                    ],
                    position: "absolute",
                    offsetBottom: "0px",
                    offsetStart: "0px",
                    offsetEnd: "0px",
                    paddingAll: "20px",
                  },
                ],
                paddingAll: "0px",
                action: {
                  type: "uri",
                  label: "action",
                  uri: "https://liff.line.me/1654061887-ZoYpPWL2",
                },
              },
            },
          },
        ])
        .then((isInClient = "success"))
        .catch(function (res) {
          isInClient = "err";
        });
    }
  }
</script>

<p>isInClient: {isInClient}</p>
<!-- <img src={picUrl} alt="" /> -->
<input bind:value={text} placeholder="input...">
<button on:click={shareMsg}>share</button>
